// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package mall

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// -------------model-------------
type Product struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId           int64    `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Subtitle             string   `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	MainImage            string   `protobuf:"bytes,4,opt,name=main_image,json=mainImage,proto3" json:"main_image,omitempty"`
	SubImages            string   `protobuf:"bytes,5,opt,name=sub_images,json=subImages,proto3" json:"sub_images,omitempty"`
	Detail               string   `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
	Price                string   `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`
	Stock                int64    `protobuf:"varint,8,opt,name=stock,proto3" json:"stock,omitempty"`
	Status               int32    `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime           string   `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_80cd7ed5c4576c11, []int{0}
}
func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (dst *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(dst, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *Product) GetSubtitle() string {
	if m != nil {
		return m.Subtitle
	}
	return ""
}

func (m *Product) GetMainImage() string {
	if m != nil {
		return m.MainImage
	}
	return ""
}

func (m *Product) GetSubImages() string {
	if m != nil {
		return m.SubImages
	}
	return ""
}

func (m *Product) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *Product) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Product) GetStock() int64 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *Product) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Product) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Product) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type Category struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId             int64    `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status               int32    `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	SortOrder            int32    `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	CreateTime           string   `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_80cd7ed5c4576c11, []int{1}
}
func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (dst *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(dst, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Category) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Category) GetSortOrder() int32 {
	if m != nil {
		return m.SortOrder
	}
	return 0
}

func (m *Category) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Category) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type Order struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo              float64  `protobuf:"fixed64,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShippingId           int64    `protobuf:"varint,4,opt,name=shipping_id,json=shippingId,proto3" json:"shipping_id,omitempty"`
	Payment              float64  `protobuf:"fixed64,5,opt,name=payment,proto3" json:"payment,omitempty"`
	PaymentType          int32    `protobuf:"varint,6,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	Postage              int32    `protobuf:"varint,7,opt,name=postage,proto3" json:"postage,omitempty"`
	Status               int32    `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	PaymentTime          string   `protobuf:"bytes,9,opt,name=payment_time,json=paymentTime,proto3" json:"payment_time,omitempty"`
	SendTime             string   `protobuf:"bytes,10,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	EndTime              string   `protobuf:"bytes,11,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	CloseTime            string   `protobuf:"bytes,12,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,13,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_80cd7ed5c4576c11, []int{2}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (dst *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(dst, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Order) GetOrderNo() float64 {
	if m != nil {
		return m.OrderNo
	}
	return 0
}

func (m *Order) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Order) GetShippingId() int64 {
	if m != nil {
		return m.ShippingId
	}
	return 0
}

func (m *Order) GetPayment() float64 {
	if m != nil {
		return m.Payment
	}
	return 0
}

func (m *Order) GetPaymentType() int32 {
	if m != nil {
		return m.PaymentType
	}
	return 0
}

func (m *Order) GetPostage() int32 {
	if m != nil {
		return m.Postage
	}
	return 0
}

func (m *Order) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Order) GetPaymentTime() string {
	if m != nil {
		return m.PaymentTime
	}
	return ""
}

func (m *Order) GetSendTime() string {
	if m != nil {
		return m.SendTime
	}
	return ""
}

func (m *Order) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *Order) GetCloseTime() string {
	if m != nil {
		return m.CloseTime
	}
	return ""
}

func (m *Order) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type PayInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo              float64  `protobuf:"fixed64,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PayPlatform          int64    `protobuf:"varint,4,opt,name=pay_platform,json=payPlatform,proto3" json:"pay_platform,omitempty"`
	PlatformNumber       string   `protobuf:"bytes,5,opt,name=platform_number,json=platformNumber,proto3" json:"platform_number,omitempty"`
	PlatformStatus       string   `protobuf:"bytes,6,opt,name=platform_status,json=platformStatus,proto3" json:"platform_status,omitempty"`
	PayAmount            float64  `protobuf:"fixed64,7,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`
	CreateTime           string   `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayInfo) Reset()         { *m = PayInfo{} }
func (m *PayInfo) String() string { return proto.CompactTextString(m) }
func (*PayInfo) ProtoMessage()    {}
func (*PayInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_80cd7ed5c4576c11, []int{3}
}
func (m *PayInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayInfo.Unmarshal(m, b)
}
func (m *PayInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayInfo.Marshal(b, m, deterministic)
}
func (dst *PayInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayInfo.Merge(dst, src)
}
func (m *PayInfo) XXX_Size() int {
	return xxx_messageInfo_PayInfo.Size(m)
}
func (m *PayInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PayInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PayInfo proto.InternalMessageInfo

func (m *PayInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PayInfo) GetOrderNo() float64 {
	if m != nil {
		return m.OrderNo
	}
	return 0
}

func (m *PayInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PayInfo) GetPayPlatform() int64 {
	if m != nil {
		return m.PayPlatform
	}
	return 0
}

func (m *PayInfo) GetPlatformNumber() string {
	if m != nil {
		return m.PlatformNumber
	}
	return ""
}

func (m *PayInfo) GetPlatformStatus() string {
	if m != nil {
		return m.PlatformStatus
	}
	return ""
}

func (m *PayInfo) GetPayAmount() float64 {
	if m != nil {
		return m.PayAmount
	}
	return 0
}

func (m *PayInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *PayInfo) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type OrderItem struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo              float64  `protobuf:"fixed64,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId            int64    `protobuf:"varint,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName          string   `protobuf:"bytes,5,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductImage         string   `protobuf:"bytes,6,opt,name=product_image,json=productImage,proto3" json:"product_image,omitempty"`
	CurrentUnitPrice     string   `protobuf:"bytes,7,opt,name=current_unit_price,json=currentUnitPrice,proto3" json:"current_unit_price,omitempty"`
	Quantity             string   `protobuf:"bytes,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TotalPrice           string   `protobuf:"bytes,9,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	CreateTime           string   `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderItem) Reset()         { *m = OrderItem{} }
func (m *OrderItem) String() string { return proto.CompactTextString(m) }
func (*OrderItem) ProtoMessage()    {}
func (*OrderItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_80cd7ed5c4576c11, []int{4}
}
func (m *OrderItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderItem.Unmarshal(m, b)
}
func (m *OrderItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderItem.Marshal(b, m, deterministic)
}
func (dst *OrderItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderItem.Merge(dst, src)
}
func (m *OrderItem) XXX_Size() int {
	return xxx_messageInfo_OrderItem.Size(m)
}
func (m *OrderItem) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderItem.DiscardUnknown(m)
}

var xxx_messageInfo_OrderItem proto.InternalMessageInfo

func (m *OrderItem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderItem) GetOrderNo() float64 {
	if m != nil {
		return m.OrderNo
	}
	return 0
}

func (m *OrderItem) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *OrderItem) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *OrderItem) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *OrderItem) GetProductImage() string {
	if m != nil {
		return m.ProductImage
	}
	return ""
}

func (m *OrderItem) GetCurrentUnitPrice() string {
	if m != nil {
		return m.CurrentUnitPrice
	}
	return ""
}

func (m *OrderItem) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *OrderItem) GetTotalPrice() string {
	if m != nil {
		return m.TotalPrice
	}
	return ""
}

func (m *OrderItem) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *OrderItem) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type Shipping struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReceiverName         string   `protobuf:"bytes,3,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	ReceiverPhone        string   `protobuf:"bytes,4,opt,name=receiver_phone,json=receiverPhone,proto3" json:"receiver_phone,omitempty"`
	ReceiverMobile       string   `protobuf:"bytes,5,opt,name=receiver_mobile,json=receiverMobile,proto3" json:"receiver_mobile,omitempty"`
	ReceiverProvince     string   `protobuf:"bytes,6,opt,name=receiver_province,json=receiverProvince,proto3" json:"receiver_province,omitempty"`
	ReceiverCity         string   `protobuf:"bytes,7,opt,name=receiver_city,json=receiverCity,proto3" json:"receiver_city,omitempty"`
	ReceiverDistrict     string   `protobuf:"bytes,8,opt,name=receiver_district,json=receiverDistrict,proto3" json:"receiver_district,omitempty"`
	ReceiverAddress      string   `protobuf:"bytes,9,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"`
	ReceiverZip          string   `protobuf:"bytes,10,opt,name=receiver_zip,json=receiverZip,proto3" json:"receiver_zip,omitempty"`
	CreateTime           string   `protobuf:"bytes,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,12,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Shipping) Reset()         { *m = Shipping{} }
func (m *Shipping) String() string { return proto.CompactTextString(m) }
func (*Shipping) ProtoMessage()    {}
func (*Shipping) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_80cd7ed5c4576c11, []int{5}
}
func (m *Shipping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shipping.Unmarshal(m, b)
}
func (m *Shipping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shipping.Marshal(b, m, deterministic)
}
func (dst *Shipping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shipping.Merge(dst, src)
}
func (m *Shipping) XXX_Size() int {
	return xxx_messageInfo_Shipping.Size(m)
}
func (m *Shipping) XXX_DiscardUnknown() {
	xxx_messageInfo_Shipping.DiscardUnknown(m)
}

var xxx_messageInfo_Shipping proto.InternalMessageInfo

func (m *Shipping) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Shipping) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Shipping) GetReceiverName() string {
	if m != nil {
		return m.ReceiverName
	}
	return ""
}

func (m *Shipping) GetReceiverPhone() string {
	if m != nil {
		return m.ReceiverPhone
	}
	return ""
}

func (m *Shipping) GetReceiverMobile() string {
	if m != nil {
		return m.ReceiverMobile
	}
	return ""
}

func (m *Shipping) GetReceiverProvince() string {
	if m != nil {
		return m.ReceiverProvince
	}
	return ""
}

func (m *Shipping) GetReceiverCity() string {
	if m != nil {
		return m.ReceiverCity
	}
	return ""
}

func (m *Shipping) GetReceiverDistrict() string {
	if m != nil {
		return m.ReceiverDistrict
	}
	return ""
}

func (m *Shipping) GetReceiverAddress() string {
	if m != nil {
		return m.ReceiverAddress
	}
	return ""
}

func (m *Shipping) GetReceiverZip() string {
	if m != nil {
		return m.ReceiverZip
	}
	return ""
}

func (m *Shipping) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Shipping) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Question             string   `protobuf:"bytes,6,opt,name=question,proto3" json:"question,omitempty"`
	Answer               string   `protobuf:"bytes,7,opt,name=answer,proto3" json:"answer,omitempty"`
	Role                 int32    `protobuf:"varint,8,opt,name=role,proto3" json:"role,omitempty"`
	CreateTime           string   `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_80cd7ed5c4576c11, []int{6}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *User) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

func (m *User) GetRole() int32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *User) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *User) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type Page struct {
	PageNum              int64    `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize             int64    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_80cd7ed5c4576c11, []int{7}
}
func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (dst *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(dst, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetPageNum() int64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *Page) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type PostProductDoReq struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostProductDoReq) Reset()         { *m = PostProductDoReq{} }
func (m *PostProductDoReq) String() string { return proto.CompactTextString(m) }
func (*PostProductDoReq) ProtoMessage()    {}
func (*PostProductDoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_80cd7ed5c4576c11, []int{8}
}
func (m *PostProductDoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostProductDoReq.Unmarshal(m, b)
}
func (m *PostProductDoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostProductDoReq.Marshal(b, m, deterministic)
}
func (dst *PostProductDoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostProductDoReq.Merge(dst, src)
}
func (m *PostProductDoReq) XXX_Size() int {
	return xxx_messageInfo_PostProductDoReq.Size(m)
}
func (m *PostProductDoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PostProductDoReq.DiscardUnknown(m)
}

var xxx_messageInfo_PostProductDoReq proto.InternalMessageInfo

func (m *PostProductDoReq) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type PostProductDoRes struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostProductDoRes) Reset()         { *m = PostProductDoRes{} }
func (m *PostProductDoRes) String() string { return proto.CompactTextString(m) }
func (*PostProductDoRes) ProtoMessage()    {}
func (*PostProductDoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_80cd7ed5c4576c11, []int{9}
}
func (m *PostProductDoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostProductDoRes.Unmarshal(m, b)
}
func (m *PostProductDoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostProductDoRes.Marshal(b, m, deterministic)
}
func (dst *PostProductDoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostProductDoRes.Merge(dst, src)
}
func (m *PostProductDoRes) XXX_Size() int {
	return xxx_messageInfo_PostProductDoRes.Size(m)
}
func (m *PostProductDoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PostProductDoRes.DiscardUnknown(m)
}

var xxx_messageInfo_PostProductDoRes proto.InternalMessageInfo

func (m *PostProductDoRes) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PostProductDoRes) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type PutProductStatusDoReq struct {
	ProductId            int64    `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutProductStatusDoReq) Reset()         { *m = PutProductStatusDoReq{} }
func (m *PutProductStatusDoReq) String() string { return proto.CompactTextString(m) }
func (*PutProductStatusDoReq) ProtoMessage()    {}
func (*PutProductStatusDoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_80cd7ed5c4576c11, []int{10}
}
func (m *PutProductStatusDoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutProductStatusDoReq.Unmarshal(m, b)
}
func (m *PutProductStatusDoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutProductStatusDoReq.Marshal(b, m, deterministic)
}
func (dst *PutProductStatusDoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutProductStatusDoReq.Merge(dst, src)
}
func (m *PutProductStatusDoReq) XXX_Size() int {
	return xxx_messageInfo_PutProductStatusDoReq.Size(m)
}
func (m *PutProductStatusDoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PutProductStatusDoReq.DiscardUnknown(m)
}

var xxx_messageInfo_PutProductStatusDoReq proto.InternalMessageInfo

func (m *PutProductStatusDoReq) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *PutProductStatusDoReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type PutProductStatusDoRes struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutProductStatusDoRes) Reset()         { *m = PutProductStatusDoRes{} }
func (m *PutProductStatusDoRes) String() string { return proto.CompactTextString(m) }
func (*PutProductStatusDoRes) ProtoMessage()    {}
func (*PutProductStatusDoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_80cd7ed5c4576c11, []int{11}
}
func (m *PutProductStatusDoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutProductStatusDoRes.Unmarshal(m, b)
}
func (m *PutProductStatusDoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutProductStatusDoRes.Marshal(b, m, deterministic)
}
func (dst *PutProductStatusDoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutProductStatusDoRes.Merge(dst, src)
}
func (m *PutProductStatusDoRes) XXX_Size() int {
	return xxx_messageInfo_PutProductStatusDoRes.Size(m)
}
func (m *PutProductStatusDoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PutProductStatusDoRes.DiscardUnknown(m)
}

var xxx_messageInfo_PutProductStatusDoRes proto.InternalMessageInfo

func (m *PutProductStatusDoRes) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PutProductStatusDoRes) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type GetProductSearchDoReq struct {
	ProductName          string   `protobuf:"bytes,1,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductId            int64    `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Page                 *Page    `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductSearchDoReq) Reset()         { *m = GetProductSearchDoReq{} }
func (m *GetProductSearchDoReq) String() string { return proto.CompactTextString(m) }
func (*GetProductSearchDoReq) ProtoMessage()    {}
func (*GetProductSearchDoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_80cd7ed5c4576c11, []int{12}
}
func (m *GetProductSearchDoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductSearchDoReq.Unmarshal(m, b)
}
func (m *GetProductSearchDoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductSearchDoReq.Marshal(b, m, deterministic)
}
func (dst *GetProductSearchDoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductSearchDoReq.Merge(dst, src)
}
func (m *GetProductSearchDoReq) XXX_Size() int {
	return xxx_messageInfo_GetProductSearchDoReq.Size(m)
}
func (m *GetProductSearchDoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductSearchDoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductSearchDoReq proto.InternalMessageInfo

func (m *GetProductSearchDoReq) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *GetProductSearchDoReq) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *GetProductSearchDoReq) GetPage() *Page {
	if m != nil {
		return m.Page
	}
	return nil
}

type GetProductSearchDoRes struct {
	Status               int32      `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Product              []*Product `protobuf:"bytes,2,rep,name=product,proto3" json:"product,omitempty"`
	Totals               int64      `protobuf:"varint,3,opt,name=totals,proto3" json:"totals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetProductSearchDoRes) Reset()         { *m = GetProductSearchDoRes{} }
func (m *GetProductSearchDoRes) String() string { return proto.CompactTextString(m) }
func (*GetProductSearchDoRes) ProtoMessage()    {}
func (*GetProductSearchDoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_80cd7ed5c4576c11, []int{13}
}
func (m *GetProductSearchDoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductSearchDoRes.Unmarshal(m, b)
}
func (m *GetProductSearchDoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductSearchDoRes.Marshal(b, m, deterministic)
}
func (dst *GetProductSearchDoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductSearchDoRes.Merge(dst, src)
}
func (m *GetProductSearchDoRes) XXX_Size() int {
	return xxx_messageInfo_GetProductSearchDoRes.Size(m)
}
func (m *GetProductSearchDoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductSearchDoRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductSearchDoRes proto.InternalMessageInfo

func (m *GetProductSearchDoRes) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetProductSearchDoRes) GetProduct() []*Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *GetProductSearchDoRes) GetTotals() int64 {
	if m != nil {
		return m.Totals
	}
	return 0
}

type GetsProductDoReq struct {
	Page                 *Page    `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetsProductDoReq) Reset()         { *m = GetsProductDoReq{} }
func (m *GetsProductDoReq) String() string { return proto.CompactTextString(m) }
func (*GetsProductDoReq) ProtoMessage()    {}
func (*GetsProductDoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_80cd7ed5c4576c11, []int{14}
}
func (m *GetsProductDoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetsProductDoReq.Unmarshal(m, b)
}
func (m *GetsProductDoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetsProductDoReq.Marshal(b, m, deterministic)
}
func (dst *GetsProductDoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetsProductDoReq.Merge(dst, src)
}
func (m *GetsProductDoReq) XXX_Size() int {
	return xxx_messageInfo_GetsProductDoReq.Size(m)
}
func (m *GetsProductDoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetsProductDoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetsProductDoReq proto.InternalMessageInfo

func (m *GetsProductDoReq) GetPage() *Page {
	if m != nil {
		return m.Page
	}
	return nil
}

type GetsProductDoRes struct {
	Status               int32      `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Product              []*Product `protobuf:"bytes,2,rep,name=product,proto3" json:"product,omitempty"`
	Totals               int64      `protobuf:"varint,3,opt,name=totals,proto3" json:"totals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetsProductDoRes) Reset()         { *m = GetsProductDoRes{} }
func (m *GetsProductDoRes) String() string { return proto.CompactTextString(m) }
func (*GetsProductDoRes) ProtoMessage()    {}
func (*GetsProductDoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_80cd7ed5c4576c11, []int{15}
}
func (m *GetsProductDoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetsProductDoRes.Unmarshal(m, b)
}
func (m *GetsProductDoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetsProductDoRes.Marshal(b, m, deterministic)
}
func (dst *GetsProductDoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetsProductDoRes.Merge(dst, src)
}
func (m *GetsProductDoRes) XXX_Size() int {
	return xxx_messageInfo_GetsProductDoRes.Size(m)
}
func (m *GetsProductDoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetsProductDoRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetsProductDoRes proto.InternalMessageInfo

func (m *GetsProductDoRes) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetsProductDoRes) GetProduct() []*Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *GetsProductDoRes) GetTotals() int64 {
	if m != nil {
		return m.Totals
	}
	return 0
}

type GetsProductReq struct {
	CategoryId           int64    `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Page                 *Page    `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Keyword              string   `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	OrderBy              string   `protobuf:"bytes,4,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	Totals               int64    `protobuf:"varint,5,opt,name=totals,proto3" json:"totals,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetsProductReq) Reset()         { *m = GetsProductReq{} }
func (m *GetsProductReq) String() string { return proto.CompactTextString(m) }
func (*GetsProductReq) ProtoMessage()    {}
func (*GetsProductReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_80cd7ed5c4576c11, []int{16}
}
func (m *GetsProductReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetsProductReq.Unmarshal(m, b)
}
func (m *GetsProductReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetsProductReq.Marshal(b, m, deterministic)
}
func (dst *GetsProductReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetsProductReq.Merge(dst, src)
}
func (m *GetsProductReq) XXX_Size() int {
	return xxx_messageInfo_GetsProductReq.Size(m)
}
func (m *GetsProductReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetsProductReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetsProductReq proto.InternalMessageInfo

func (m *GetsProductReq) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *GetsProductReq) GetPage() *Page {
	if m != nil {
		return m.Page
	}
	return nil
}

func (m *GetsProductReq) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *GetsProductReq) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

func (m *GetsProductReq) GetTotals() int64 {
	if m != nil {
		return m.Totals
	}
	return 0
}

type GetsProductRes struct {
	Status               int32      `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Products             []*Product `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetsProductRes) Reset()         { *m = GetsProductRes{} }
func (m *GetsProductRes) String() string { return proto.CompactTextString(m) }
func (*GetsProductRes) ProtoMessage()    {}
func (*GetsProductRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_80cd7ed5c4576c11, []int{17}
}
func (m *GetsProductRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetsProductRes.Unmarshal(m, b)
}
func (m *GetsProductRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetsProductRes.Marshal(b, m, deterministic)
}
func (dst *GetsProductRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetsProductRes.Merge(dst, src)
}
func (m *GetsProductRes) XXX_Size() int {
	return xxx_messageInfo_GetsProductRes.Size(m)
}
func (m *GetsProductRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetsProductRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetsProductRes proto.InternalMessageInfo

func (m *GetsProductRes) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetsProductRes) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type GetProductByIdReq struct {
	ProductId            int64    `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductByIdReq) Reset()         { *m = GetProductByIdReq{} }
func (m *GetProductByIdReq) String() string { return proto.CompactTextString(m) }
func (*GetProductByIdReq) ProtoMessage()    {}
func (*GetProductByIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_80cd7ed5c4576c11, []int{18}
}
func (m *GetProductByIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductByIdReq.Unmarshal(m, b)
}
func (m *GetProductByIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductByIdReq.Marshal(b, m, deterministic)
}
func (dst *GetProductByIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductByIdReq.Merge(dst, src)
}
func (m *GetProductByIdReq) XXX_Size() int {
	return xxx_messageInfo_GetProductByIdReq.Size(m)
}
func (m *GetProductByIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductByIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductByIdReq proto.InternalMessageInfo

func (m *GetProductByIdReq) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

type GetProductByIdRes struct {
	Status               int32      `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Product              []*Product `protobuf:"bytes,2,rep,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetProductByIdRes) Reset()         { *m = GetProductByIdRes{} }
func (m *GetProductByIdRes) String() string { return proto.CompactTextString(m) }
func (*GetProductByIdRes) ProtoMessage()    {}
func (*GetProductByIdRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_80cd7ed5c4576c11, []int{19}
}
func (m *GetProductByIdRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductByIdRes.Unmarshal(m, b)
}
func (m *GetProductByIdRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductByIdRes.Marshal(b, m, deterministic)
}
func (dst *GetProductByIdRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductByIdRes.Merge(dst, src)
}
func (m *GetProductByIdRes) XXX_Size() int {
	return xxx_messageInfo_GetProductByIdRes.Size(m)
}
func (m *GetProductByIdRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductByIdRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductByIdRes proto.InternalMessageInfo

func (m *GetProductByIdRes) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetProductByIdRes) GetProduct() []*Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "mall.Product")
	proto.RegisterType((*Category)(nil), "mall.Category")
	proto.RegisterType((*Order)(nil), "mall.Order")
	proto.RegisterType((*PayInfo)(nil), "mall.PayInfo")
	proto.RegisterType((*OrderItem)(nil), "mall.OrderItem")
	proto.RegisterType((*Shipping)(nil), "mall.Shipping")
	proto.RegisterType((*User)(nil), "mall.User")
	proto.RegisterType((*Page)(nil), "mall.Page")
	proto.RegisterType((*PostProductDoReq)(nil), "mall.PostProductDoReq")
	proto.RegisterType((*PostProductDoRes)(nil), "mall.PostProductDoRes")
	proto.RegisterType((*PutProductStatusDoReq)(nil), "mall.PutProductStatusDoReq")
	proto.RegisterType((*PutProductStatusDoRes)(nil), "mall.PutProductStatusDoRes")
	proto.RegisterType((*GetProductSearchDoReq)(nil), "mall.GetProductSearchDoReq")
	proto.RegisterType((*GetProductSearchDoRes)(nil), "mall.GetProductSearchDoRes")
	proto.RegisterType((*GetsProductDoReq)(nil), "mall.GetsProductDoReq")
	proto.RegisterType((*GetsProductDoRes)(nil), "mall.GetsProductDoRes")
	proto.RegisterType((*GetsProductReq)(nil), "mall.GetsProductReq")
	proto.RegisterType((*GetsProductRes)(nil), "mall.GetsProductRes")
	proto.RegisterType((*GetProductByIdReq)(nil), "mall.GetProductByIdReq")
	proto.RegisterType((*GetProductByIdRes)(nil), "mall.GetProductByIdRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	Gets(ctx context.Context, in *GetsProductReq, opts ...grpc.CallOption) (*GetsProductRes, error)
	GeById(ctx context.Context, in *GetProductByIdReq, opts ...grpc.CallOption) (*GetProductByIdRes, error)
	GetsDo(ctx context.Context, in *GetsProductDoReq, opts ...grpc.CallOption) (*GetsProductDoRes, error)
	GetSearchDo(ctx context.Context, in *GetProductSearchDoReq, opts ...grpc.CallOption) (*GetProductSearchDoRes, error)
	PutStatusDo(ctx context.Context, in *PutProductStatusDoReq, opts ...grpc.CallOption) (*PutProductStatusDoRes, error)
	PostProductDo(ctx context.Context, in *PostProductDoReq, opts ...grpc.CallOption) (*PostProductDoRes, error)
}

type productServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductServiceClient(cc *grpc.ClientConn) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) Gets(ctx context.Context, in *GetsProductReq, opts ...grpc.CallOption) (*GetsProductRes, error) {
	out := new(GetsProductRes)
	err := c.cc.Invoke(ctx, "/mall.ProductService/Gets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GeById(ctx context.Context, in *GetProductByIdReq, opts ...grpc.CallOption) (*GetProductByIdRes, error) {
	out := new(GetProductByIdRes)
	err := c.cc.Invoke(ctx, "/mall.ProductService/GeById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetsDo(ctx context.Context, in *GetsProductDoReq, opts ...grpc.CallOption) (*GetsProductDoRes, error) {
	out := new(GetsProductDoRes)
	err := c.cc.Invoke(ctx, "/mall.ProductService/GetsDo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetSearchDo(ctx context.Context, in *GetProductSearchDoReq, opts ...grpc.CallOption) (*GetProductSearchDoRes, error) {
	out := new(GetProductSearchDoRes)
	err := c.cc.Invoke(ctx, "/mall.ProductService/GetSearchDo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) PutStatusDo(ctx context.Context, in *PutProductStatusDoReq, opts ...grpc.CallOption) (*PutProductStatusDoRes, error) {
	out := new(PutProductStatusDoRes)
	err := c.cc.Invoke(ctx, "/mall.ProductService/PutStatusDo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) PostProductDo(ctx context.Context, in *PostProductDoReq, opts ...grpc.CallOption) (*PostProductDoRes, error) {
	out := new(PostProductDoRes)
	err := c.cc.Invoke(ctx, "/mall.ProductService/PostProductDo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	Gets(context.Context, *GetsProductReq) (*GetsProductRes, error)
	GeById(context.Context, *GetProductByIdReq) (*GetProductByIdRes, error)
	GetsDo(context.Context, *GetsProductDoReq) (*GetsProductDoRes, error)
	GetSearchDo(context.Context, *GetProductSearchDoReq) (*GetProductSearchDoRes, error)
	PutStatusDo(context.Context, *PutProductStatusDoReq) (*PutProductStatusDoRes, error)
	PostProductDo(context.Context, *PostProductDoReq) (*PostProductDoRes, error)
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_Gets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetsProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).Gets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mall.ProductService/Gets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).Gets(ctx, req.(*GetsProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GeById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GeById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mall.ProductService/GeById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GeById(ctx, req.(*GetProductByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetsDo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetsProductDoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetsDo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mall.ProductService/GetsDo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetsDo(ctx, req.(*GetsProductDoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetSearchDo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductSearchDoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetSearchDo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mall.ProductService/GetSearchDo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetSearchDo(ctx, req.(*GetProductSearchDoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_PutStatusDo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutProductStatusDoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).PutStatusDo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mall.ProductService/PutStatusDo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).PutStatusDo(ctx, req.(*PutProductStatusDoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_PostProductDo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostProductDoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).PostProductDo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mall.ProductService/PostProductDo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).PostProductDo(ctx, req.(*PostProductDoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mall.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Gets",
			Handler:    _ProductService_Gets_Handler,
		},
		{
			MethodName: "GeById",
			Handler:    _ProductService_GeById_Handler,
		},
		{
			MethodName: "GetsDo",
			Handler:    _ProductService_GetsDo_Handler,
		},
		{
			MethodName: "GetSearchDo",
			Handler:    _ProductService_GetSearchDo_Handler,
		},
		{
			MethodName: "PutStatusDo",
			Handler:    _ProductService_PutStatusDo_Handler,
		},
		{
			MethodName: "PostProductDo",
			Handler:    _ProductService_PostProductDo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_demo_80cd7ed5c4576c11) }

var fileDescriptor_demo_80cd7ed5c4576c11 = []byte{
	// 1252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xcd, 0x6e, 0xdb, 0xc6,
	0x13, 0x0f, 0xa9, 0x2f, 0x72, 0x64, 0xfb, 0xef, 0x10, 0xf9, 0x50, 0x14, 0xe4, 0x5f, 0x97, 0x41,
	0x91, 0x04, 0x2d, 0x72, 0x70, 0x7b, 0x6a, 0x8b, 0x00, 0x49, 0x0c, 0x18, 0x3a, 0xd4, 0x15, 0x68,
	0xe7, 0xd2, 0x8b, 0x40, 0x89, 0x1b, 0x79, 0x61, 0x91, 0xcb, 0x70, 0x97, 0x0e, 0xe4, 0x73, 0x5f,
	0xa2, 0x87, 0x9e, 0xfa, 0x06, 0xbd, 0xf4, 0x05, 0xfa, 0x26, 0x7d, 0x87, 0x9e, 0x8b, 0xd9, 0x2f,
	0xf1, 0x43, 0x8e, 0x51, 0x24, 0xbd, 0x69, 0x7e, 0xb3, 0x33, 0x3b, 0xf3, 0x9b, 0xd9, 0x19, 0x0a,
	0x20, 0x21, 0x29, 0x7b, 0x9e, 0x17, 0x4c, 0xb0, 0xa0, 0x9b, 0xc6, 0xab, 0x55, 0xf8, 0xbb, 0x0b,
	0x83, 0x69, 0xc1, 0x92, 0x72, 0x21, 0x82, 0x3d, 0x70, 0x69, 0x32, 0x72, 0x0e, 0x9c, 0xa7, 0x9d,
	0xc8, 0xa5, 0x49, 0xf0, 0x19, 0x0c, 0x17, 0xb1, 0x20, 0x4b, 0x56, 0xac, 0x67, 0x34, 0x19, 0xb9,
	0x52, 0x01, 0x06, 0x9a, 0x24, 0xc1, 0x18, 0x3c, 0x5e, 0xce, 0x05, 0x15, 0x2b, 0x32, 0xea, 0x1c,
	0x38, 0x4f, 0xfd, 0xc8, 0xca, 0xc1, 0x23, 0x80, 0x34, 0xa6, 0xd9, 0x8c, 0xa6, 0xf1, 0x92, 0x8c,
	0xba, 0x52, 0xeb, 0x23, 0x32, 0x41, 0x00, 0xd5, 0xbc, 0x9c, 0x2b, 0x2d, 0x1f, 0xf5, 0x94, 0x9a,
	0x97, 0x73, 0xa9, 0xe5, 0xc1, 0x3d, 0xe8, 0x27, 0x44, 0xc4, 0x74, 0x35, 0xea, 0x4b, 0x95, 0x96,
	0x82, 0x3b, 0xd0, 0xcb, 0x0b, 0xba, 0x20, 0xa3, 0x81, 0x84, 0x95, 0x80, 0x28, 0x17, 0x6c, 0x71,
	0x31, 0xf2, 0x64, 0x88, 0x4a, 0x40, 0x1f, 0x5c, 0xc4, 0xa2, 0xe4, 0x23, 0xff, 0xc0, 0x79, 0xda,
	0x8b, 0xb4, 0x24, 0xd3, 0x2a, 0x48, 0x2c, 0xc8, 0x4c, 0xd0, 0x94, 0x8c, 0x40, 0x7a, 0x02, 0x05,
	0x9d, 0xd1, 0x94, 0xe0, 0x81, 0x32, 0x4f, 0xec, 0x81, 0xa1, 0x3a, 0xa0, 0x20, 0x3c, 0x10, 0xfe,
	0xe9, 0x80, 0xf7, 0x5a, 0xd3, 0xd0, 0x62, 0xed, 0x21, 0xf8, 0x79, 0x5c, 0x90, 0x4c, 0x6c, 0x38,
	0xf3, 0x14, 0x30, 0x49, 0x82, 0x00, 0xba, 0x59, 0x9c, 0x1a, 0xb6, 0xe4, 0xef, 0x4a, 0x9c, 0xdd,
	0x5a, 0x9c, 0x48, 0x11, 0x2b, 0xc4, 0x8c, 0x15, 0x09, 0x29, 0x24, 0x45, 0xbd, 0xc8, 0x47, 0xe4,
	0x47, 0x04, 0x9a, 0x69, 0xf4, 0x6f, 0x4a, 0x63, 0xd0, 0x4a, 0xe3, 0x6f, 0x17, 0x7a, 0xca, 0x57,
	0x33, 0x87, 0x07, 0xe0, 0xc9, 0x5b, 0x67, 0x19, 0x93, 0x29, 0x38, 0xd1, 0x40, 0xca, 0x27, 0x2c,
	0xb8, 0x0f, 0x83, 0x92, 0x93, 0x02, 0x93, 0xeb, 0xc8, 0xf3, 0x7d, 0x14, 0x27, 0xb2, 0x5b, 0xf8,
	0x39, 0xcd, 0x73, 0x9a, 0x2d, 0x51, 0xd9, 0x55, 0xdd, 0x62, 0xa0, 0x49, 0x12, 0x8c, 0x60, 0x90,
	0xc7, 0xeb, 0x94, 0x64, 0x42, 0x26, 0xe3, 0x44, 0x46, 0x0c, 0x3e, 0x87, 0x1d, 0xfd, 0x73, 0x26,
	0xd6, 0xb9, 0xca, 0xa5, 0x17, 0x0d, 0x35, 0x76, 0xb6, 0xce, 0x89, 0x34, 0x66, 0x5c, 0x60, 0x2f,
	0x0d, 0xa4, 0xd6, 0x88, 0x15, 0xfa, 0xbc, 0x1a, 0x7d, 0x55, 0xa7, 0x98, 0xbf, 0x2f, 0xf3, 0xb7,
	0x4e, 0x91, 0xa1, 0x87, 0xe0, 0x73, 0x92, 0x25, 0xd5, 0x3e, 0xf0, 0x10, 0x90, 0xca, 0x07, 0xe0,
	0x59, 0x9d, 0x6a, 0x81, 0x81, 0x51, 0x3d, 0x02, 0x58, 0xac, 0x18, 0xd7, 0xc4, 0xee, 0xa8, 0xe6,
	0x95, 0xc8, 0x36, 0xe2, 0x77, 0x5b, 0xc4, 0xff, 0x86, 0x8f, 0x2e, 0x5e, 0x4f, 0xb2, 0xb7, 0xec,
	0x93, 0x50, 0xaf, 0x52, 0x9d, 0xe5, 0xab, 0x58, 0xbc, 0x65, 0x45, 0xaa, 0xb9, 0xc7, 0x54, 0xa7,
	0x1a, 0x0a, 0x9e, 0xc0, 0xff, 0x8c, 0x7a, 0x96, 0x95, 0xe9, 0x5c, 0x77, 0x94, 0x1f, 0xed, 0x19,
	0xf8, 0x44, 0xa2, 0xb5, 0x83, 0x9a, 0xd7, 0x7e, 0xfd, 0xe0, 0xa9, 0x6d, 0x4f, 0xbc, 0x34, 0x4e,
	0x59, 0x99, 0x09, 0x59, 0x14, 0x27, 0xf2, 0xf3, 0x78, 0xfd, 0x52, 0x02, 0xcd, 0xf6, 0xf4, 0x6e,
	0x6a, 0x4f, 0xbf, 0xc5, 0xd2, 0x5f, 0x2e, 0xf8, 0xb2, 0x3d, 0x27, 0x82, 0xa4, 0x9f, 0x84, 0x27,
	0x0c, 0x59, 0xcd, 0xba, 0x4d, 0x87, 0xfa, 0x1a, 0xd1, 0x34, 0x6a, 0xb5, 0x7c, 0xa4, 0x3d, 0xdd,
	0x31, 0x0a, 0x3b, 0xc1, 0xb7, 0xfa, 0x18, 0x76, 0xad, 0x07, 0x39, 0xd8, 0x14, 0x37, 0xc6, 0x4e,
	0xcd, 0xb6, 0xaf, 0x20, 0x58, 0x94, 0x85, 0x1c, 0x01, 0x65, 0x46, 0xc5, 0xac, 0x3a, 0xb1, 0xf6,
	0xb5, 0xe6, 0x4d, 0x46, 0xc5, 0x54, 0x0e, 0xaf, 0x31, 0x78, 0xef, 0xca, 0x38, 0x13, 0x54, 0xac,
	0x35, 0x4b, 0x56, 0x46, 0x8e, 0x04, 0x13, 0xf1, 0x4a, 0xbb, 0xd0, 0x1c, 0x49, 0x48, 0x19, 0x7f,
	0xfc, 0x2c, 0xfb, 0xa3, 0x03, 0xde, 0xa9, 0x7e, 0xa4, 0x2d, 0x92, 0x2b, 0x4c, 0xba, 0x35, 0x26,
	0x1f, 0xc3, 0x6e, 0x41, 0x16, 0x84, 0x5e, 0x62, 0x01, 0x36, 0x03, 0x6d, 0xc7, 0x80, 0x92, 0xac,
	0x2f, 0x60, 0xcf, 0x1e, 0xca, 0xcf, 0x59, 0x66, 0xd6, 0x80, 0x35, 0x9d, 0x22, 0x88, 0x1d, 0x67,
	0x8f, 0xa5, 0x6c, 0x4e, 0x57, 0x86, 0x79, 0x6b, 0xfd, 0x83, 0x44, 0x83, 0x2f, 0xe1, 0xf6, 0xc6,
	0x5f, 0xc1, 0x2e, 0x69, 0xb6, 0x30, 0x05, 0xd8, 0xb7, 0x2e, 0x35, 0x5e, 0x8b, 0x70, 0x81, 0xdc,
	0x0e, 0xea, 0x11, 0xbe, 0x46, 0x7e, 0xab, 0x1e, 0x13, 0xca, 0x45, 0x41, 0x17, 0x42, 0x17, 0xc1,
	0x7a, 0x3c, 0xd2, 0x78, 0xf0, 0x0c, 0x2c, 0x36, 0x8b, 0x93, 0xa4, 0x20, 0x9c, 0xeb, 0x8a, 0xd8,
	0xf8, 0x5f, 0x2a, 0x18, 0x3b, 0xc9, 0x1e, 0xbd, 0xa2, 0xb9, 0xae, 0xcb, 0xd0, 0x60, 0x3f, 0xd1,
	0xbc, 0x59, 0xb9, 0xe1, 0x4d, 0x95, 0xdb, 0x69, 0x55, 0xee, 0x67, 0x17, 0xba, 0x6f, 0xf8, 0x96,
	0xe9, 0x3d, 0x06, 0x0f, 0xcb, 0x24, 0xeb, 0xe2, 0xaa, 0x8e, 0x32, 0x32, 0xea, 0xf2, 0x98, 0xf3,
	0xf7, 0xac, 0x48, 0xcc, 0xca, 0x36, 0x32, 0xae, 0x51, 0x92, 0xe2, 0xce, 0x55, 0x65, 0x52, 0x82,
	0x5c, 0xb9, 0xb2, 0x78, 0x3d, 0xbd, 0x72, 0x65, 0xd1, 0x64, 0xd7, 0x12, 0x2e, 0x28, 0xcb, 0x74,
	0x09, 0xac, 0x8c, 0x13, 0x39, 0xce, 0xf8, 0x7b, 0x52, 0x68, 0xce, 0xb5, 0x84, 0xcb, 0xaf, 0x60,
	0x2b, 0xa2, 0xe7, 0xb4, 0xfc, 0xdd, 0xa4, 0xc1, 0xbf, 0x89, 0x06, 0x68, 0xd1, 0xf0, 0x02, 0xba,
	0x53, 0x7c, 0x75, 0x0f, 0x30, 0xb3, 0x25, 0xc1, 0xe9, 0xa6, 0xb9, 0x18, 0xa0, 0x7c, 0x52, 0xa6,
	0x6a, 0x25, 0x2f, 0xc9, 0x8c, 0xd3, 0x2b, 0xb2, 0x59, 0xc9, 0x4b, 0x72, 0x4a, 0xaf, 0x48, 0xf8,
	0x1d, 0xec, 0x4f, 0x19, 0x17, 0xfa, 0x23, 0xe8, 0x88, 0x45, 0xe4, 0x5d, 0xf0, 0x04, 0x06, 0xfa,
	0x45, 0x4b, 0x57, 0xc3, 0xc3, 0xdd, 0xe7, 0xf8, 0xb5, 0xf4, 0x5c, 0x1f, 0x8a, 0x8c, 0x36, 0x7c,
	0xd1, 0x32, 0xe6, 0x95, 0x85, 0xe4, 0xd4, 0x16, 0x52, 0x00, 0xdd, 0x24, 0x16, 0xb1, 0x2e, 0x89,
	0xfc, 0x1d, 0x9e, 0xc0, 0xdd, 0x69, 0x69, 0xcc, 0xd5, 0x60, 0x55, 0x11, 0xd4, 0x47, 0x95, 0xd3,
	0x1c, 0x55, 0x9b, 0x3b, 0xdc, 0xea, 0x1d, 0xe1, 0xeb, 0xed, 0xfe, 0xfe, 0x5d, 0x50, 0x6b, 0xb8,
	0x7b, 0x4c, 0xac, 0x13, 0x12, 0x17, 0x8b, 0x73, 0x15, 0x54, 0x73, 0x40, 0x3a, 0xed, 0x01, 0x59,
	0x8f, 0xdb, 0x6d, 0xc6, 0xfd, 0x7f, 0xe8, 0x22, 0xf1, 0xb2, 0xf5, 0x86, 0x87, 0xa0, 0x59, 0x8d,
	0x97, 0x24, 0x92, 0x78, 0x98, 0x6f, 0xbf, 0xfa, 0xfa, 0xf8, 0x2b, 0x95, 0x72, 0x0f, 0x3a, 0xd7,
	0x57, 0x0a, 0x1d, 0xc8, 0xb9, 0xc9, 0xcd, 0x4e, 0x50, 0x52, 0x78, 0x08, 0xfb, 0xc7, 0x44, 0xf0,
	0x5a, 0xf9, 0x4d, 0x94, 0xce, 0x35, 0x51, 0x5e, 0xb4, 0x6c, 0xfe, 0xc3, 0x00, 0x7f, 0x75, 0x60,
	0xaf, 0x72, 0x1b, 0xc6, 0xd7, 0xf8, 0x30, 0x77, 0x5a, 0x1f, 0xe6, 0x26, 0x01, 0x77, 0x7b, 0x02,
	0xf8, 0x35, 0x75, 0x41, 0xd6, 0x95, 0x21, 0x60, 0x44, 0xd4, 0xc8, 0x35, 0xfa, 0x6a, 0xad, 0xa7,
	0x80, 0x11, 0x2b, 0xf1, 0xf5, 0x6a, 0xf1, 0x9d, 0x36, 0xc2, 0xbb, 0x9e, 0x8a, 0x67, 0xe0, 0xe9,
	0x64, 0xf9, 0x76, 0x2e, 0xac, 0x3a, 0x3c, 0x84, 0xdb, 0x9b, 0x3e, 0x78, 0xb5, 0x9e, 0x24, 0x37,
	0xbf, 0x89, 0xf0, 0xac, 0x6d, 0xf3, 0xf1, 0x65, 0x39, 0xfc, 0xa5, 0x03, 0x7b, 0xb6, 0x1f, 0x8b,
	0x4b, 0x5c, 0xba, 0xdf, 0x40, 0x17, 0x33, 0x0e, 0xee, 0x28, 0x93, 0x7a, 0x71, 0xc6, 0xdb, 0x50,
	0x1e, 0xde, 0x0a, 0xbe, 0x87, 0xfe, 0x31, 0xc1, 0xb0, 0x82, 0xfb, 0xf6, 0x44, 0x3d, 0xc1, 0xf1,
	0x35, 0x0a, 0xb4, 0xfe, 0x16, 0xad, 0x05, 0x3f, 0x62, 0xc1, 0xbd, 0x96, 0x7f, 0xd9, 0xb4, 0xe3,
	0xed, 0x38, 0xda, 0x4e, 0x60, 0x78, 0x4c, 0xec, 0x6b, 0x0a, 0x1e, 0x36, 0x6f, 0xa9, 0x3c, 0xf1,
	0xf1, 0x07, 0x94, 0xda, 0xd5, 0xb4, 0xb4, 0x83, 0xc5, 0xb8, 0xda, 0x3a, 0xc2, 0xc6, 0x1f, 0x50,
	0xa2, 0xab, 0x97, 0xb0, 0x5b, 0x1b, 0x9d, 0x26, 0xb1, 0xe6, 0x30, 0x1e, 0x6f, 0xc7, 0x79, 0x78,
	0x6b, 0xde, 0x97, 0xff, 0x64, 0xbf, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0x95, 0x12, 0xce, 0x06,
	0xd7, 0x0e, 0x00, 0x00,
}
