// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v4.0.0
// source: companyIntro.proto

package companyIntro

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// getAll 的req 和resp
type RequestGetAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Page   *Page `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *RequestGetAll) Reset() {
	*x = RequestGetAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_companyIntro_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGetAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetAll) ProtoMessage() {}

func (x *RequestGetAll) ProtoReflect() protoreflect.Message {
	mi := &file_companyIntro_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetAll.ProtoReflect.Descriptor instead.
func (*RequestGetAll) Descriptor() ([]byte, []int) {
	return file_companyIntro_proto_rawDescGZIP(), []int{0}
}

func (x *RequestGetAll) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RequestGetAll) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type ResponseGetAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompanyIntro []*CompanyIntro `protobuf:"bytes,1,rep,name=companyIntro,proto3" json:"companyIntro,omitempty"`
	Page         *Page           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ResponseGetAll) Reset() {
	*x = ResponseGetAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_companyIntro_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGetAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetAll) ProtoMessage() {}

func (x *ResponseGetAll) ProtoReflect() protoreflect.Message {
	mi := &file_companyIntro_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetAll.ProtoReflect.Descriptor instead.
func (*ResponseGetAll) Descriptor() ([]byte, []int) {
	return file_companyIntro_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseGetAll) GetCompanyIntro() []*CompanyIntro {
	if x != nil {
		return x.CompanyIntro
	}
	return nil
}

func (x *ResponseGetAll) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

// 分页数据
type Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageNum   int32 `protobuf:"varint,1,opt,name=PageNum,proto3" json:"PageNum,omitempty"`
	PageSize  int32 `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	Total     int32 `protobuf:"varint,3,opt,name=Total,proto3" json:"Total,omitempty"`
	PageTotal int32 `protobuf:"varint,4,opt,name=PageTotal,proto3" json:"PageTotal,omitempty"`
}

func (x *Page) Reset() {
	*x = Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_companyIntro_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_companyIntro_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_companyIntro_proto_rawDescGZIP(), []int{2}
}

func (x *Page) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *Page) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Page) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Page) GetPageTotal() int32 {
	if x != nil {
		return x.PageTotal
	}
	return 0
}

// 结构体
type CompanyIntro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	Status  int32  `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`
	SeqNo   int64  `protobuf:"varint,5,opt,name=SeqNo,proto3" json:"SeqNo,omitempty"`
}

func (x *CompanyIntro) Reset() {
	*x = CompanyIntro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_companyIntro_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompanyIntro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyIntro) ProtoMessage() {}

func (x *CompanyIntro) ProtoReflect() protoreflect.Message {
	mi := &file_companyIntro_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyIntro.ProtoReflect.Descriptor instead.
func (*CompanyIntro) Descriptor() ([]byte, []int) {
	return file_companyIntro_proto_rawDescGZIP(), []int{3}
}

func (x *CompanyIntro) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CompanyIntro) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CompanyIntro) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CompanyIntro) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CompanyIntro) GetSeqNo() int64 {
	if x != nil {
		return x.SeqNo
	}
	return 0
}

// GetI 的 req and resp
type RequestGetI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequestGetI) Reset() {
	*x = RequestGetI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_companyIntro_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGetI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetI) ProtoMessage() {}

func (x *RequestGetI) ProtoReflect() protoreflect.Message {
	mi := &file_companyIntro_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetI.ProtoReflect.Descriptor instead.
func (*RequestGetI) Descriptor() ([]byte, []int) {
	return file_companyIntro_proto_rawDescGZIP(), []int{4}
}

type ResponseGetI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompanyIntro []*CompanyIntro `protobuf:"bytes,1,rep,name=companyIntro,proto3" json:"companyIntro,omitempty"`
	Page         *Page           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ResponseGetI) Reset() {
	*x = ResponseGetI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_companyIntro_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGetI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetI) ProtoMessage() {}

func (x *ResponseGetI) ProtoReflect() protoreflect.Message {
	mi := &file_companyIntro_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetI.ProtoReflect.Descriptor instead.
func (*ResponseGetI) Descriptor() ([]byte, []int) {
	return file_companyIntro_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseGetI) GetCompanyIntro() []*CompanyIntro {
	if x != nil {
		return x.CompanyIntro
	}
	return nil
}

func (x *ResponseGetI) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_companyIntro_proto protoreflect.FileDescriptor

var file_companyIntro_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x6e, 0x74,
	0x72, 0x6f, 0x22, 0x4f, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x26, 0x0a, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x22, 0x78, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x3e, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x49, 0x6e, 0x74, 0x72, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x49, 0x6e, 0x74, 0x72, 0x6f, 0x12, 0x26, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x6e, 0x74,
	0x72, 0x6f, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x70, 0x0a,
	0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x50, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22,
	0x7c, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x65, 0x71, 0x4e, 0x6f,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x53, 0x65, 0x71, 0x4e, 0x6f, 0x22, 0x0d, 0x0a,
	0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x49, 0x22, 0x76, 0x0a, 0x0c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x49, 0x12, 0x3e, 0x0a, 0x0c,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x6e, 0x74, 0x72,
	0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x52, 0x0c,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x12, 0x26, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x32, 0x96, 0x01, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x49, 0x6e, 0x74, 0x72, 0x6f, 0x12, 0x3f, 0x0a, 0x04, 0x47, 0x65, 0x74, 0x49, 0x12, 0x19, 0x2e,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x49, 0x1a, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x47, 0x65, 0x74, 0x49, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x12, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x1a, 0x1c, 0x2e,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x22, 0x00, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_companyIntro_proto_rawDescOnce sync.Once
	file_companyIntro_proto_rawDescData = file_companyIntro_proto_rawDesc
)

func file_companyIntro_proto_rawDescGZIP() []byte {
	file_companyIntro_proto_rawDescOnce.Do(func() {
		file_companyIntro_proto_rawDescData = protoimpl.X.CompressGZIP(file_companyIntro_proto_rawDescData)
	})
	return file_companyIntro_proto_rawDescData
}

var file_companyIntro_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_companyIntro_proto_goTypes = []interface{}{
	(*RequestGetAll)(nil),  // 0: companyIntro.RequestGetAll
	(*ResponseGetAll)(nil), // 1: companyIntro.ResponseGetAll
	(*Page)(nil),           // 2: companyIntro.Page
	(*CompanyIntro)(nil),   // 3: companyIntro.CompanyIntro
	(*RequestGetI)(nil),    // 4: companyIntro.RequestGetI
	(*ResponseGetI)(nil),   // 5: companyIntro.ResponseGetI
}
var file_companyIntro_proto_depIdxs = []int32{
	2, // 0: companyIntro.RequestGetAll.page:type_name -> companyIntro.Page
	3, // 1: companyIntro.ResponseGetAll.companyIntro:type_name -> companyIntro.CompanyIntro
	2, // 2: companyIntro.ResponseGetAll.page:type_name -> companyIntro.Page
	3, // 3: companyIntro.ResponseGetI.companyIntro:type_name -> companyIntro.CompanyIntro
	2, // 4: companyIntro.ResponseGetI.page:type_name -> companyIntro.Page
	4, // 5: companyIntro.companyIntro.GetI:input_type -> companyIntro.RequestGetI
	0, // 6: companyIntro.companyIntro.GetAll:input_type -> companyIntro.RequestGetAll
	5, // 7: companyIntro.companyIntro.GetI:output_type -> companyIntro.ResponseGetI
	1, // 8: companyIntro.companyIntro.GetAll:output_type -> companyIntro.ResponseGetAll
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_companyIntro_proto_init() }
func file_companyIntro_proto_init() {
	if File_companyIntro_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_companyIntro_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGetAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_companyIntro_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGetAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_companyIntro_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_companyIntro_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompanyIntro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_companyIntro_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGetI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_companyIntro_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGetI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_companyIntro_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_companyIntro_proto_goTypes,
		DependencyIndexes: file_companyIntro_proto_depIdxs,
		MessageInfos:      file_companyIntro_proto_msgTypes,
	}.Build()
	File_companyIntro_proto = out.File
	file_companyIntro_proto_rawDesc = nil
	file_companyIntro_proto_goTypes = nil
	file_companyIntro_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CompanyIntroClient is the client API for CompanyIntro service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CompanyIntroClient interface {
	GetI(ctx context.Context, in *RequestGetI, opts ...grpc.CallOption) (*ResponseGetI, error)
	GetAll(ctx context.Context, in *RequestGetAll, opts ...grpc.CallOption) (*ResponseGetAll, error)
}

type companyIntroClient struct {
	cc grpc.ClientConnInterface
}

func NewCompanyIntroClient(cc grpc.ClientConnInterface) CompanyIntroClient {
	return &companyIntroClient{cc}
}

func (c *companyIntroClient) GetI(ctx context.Context, in *RequestGetI, opts ...grpc.CallOption) (*ResponseGetI, error) {
	out := new(ResponseGetI)
	err := c.cc.Invoke(ctx, "/companyIntro.companyIntro/GetI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companyIntroClient) GetAll(ctx context.Context, in *RequestGetAll, opts ...grpc.CallOption) (*ResponseGetAll, error) {
	out := new(ResponseGetAll)
	err := c.cc.Invoke(ctx, "/companyIntro.companyIntro/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompanyIntroServer is the server API for CompanyIntro service.
type CompanyIntroServer interface {
	GetI(context.Context, *RequestGetI) (*ResponseGetI, error)
	GetAll(context.Context, *RequestGetAll) (*ResponseGetAll, error)
}

// UnimplementedCompanyIntroServer can be embedded to have forward compatible implementations.
type UnimplementedCompanyIntroServer struct {
}

func (*UnimplementedCompanyIntroServer) GetI(context.Context, *RequestGetI) (*ResponseGetI, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetI not implemented")
}
func (*UnimplementedCompanyIntroServer) GetAll(context.Context, *RequestGetAll) (*ResponseGetAll, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}

func RegisterCompanyIntroServer(s *grpc.Server, srv CompanyIntroServer) {
	s.RegisterService(&_CompanyIntro_serviceDesc, srv)
}

func _CompanyIntro_GetI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGetI)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyIntroServer).GetI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/companyIntro.companyIntro/GetI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyIntroServer).GetI(ctx, req.(*RequestGetI))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompanyIntro_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGetAll)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyIntroServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/companyIntro.companyIntro/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyIntroServer).GetAll(ctx, req.(*RequestGetAll))
	}
	return interceptor(ctx, in, info, handler)
}

var _CompanyIntro_serviceDesc = grpc.ServiceDesc{
	ServiceName: "companyIntro.companyIntro",
	HandlerType: (*CompanyIntroServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetI",
			Handler:    _CompanyIntro_GetI_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _CompanyIntro_GetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "companyIntro.proto",
}
